@startuml
class com.example.hgym.listViewRollActivity {
~ FirebaseFirestore db
~ ListView lvMethods
~ ArrayList<trainerForListView> alMethods
- TextView putRoll
- FirebaseAuth mAuth
# void onCreate(Bundle)
- void loadGamesToListView()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.hgym.MainActivity {
~ Button btn
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.userDetailsByRollActivity {
~ Button btnGoBack
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.group {
- String date
- String hour
- String minute
- int duration
- String emailOfTrainer
- ArrayList<user> participants
- String exp
+ <<Create>> group(String,String,String,String,int,String,ArrayList<user>)
+ <<Create>> group(String,String,String,String,int,String)
+ <<Create>> group()
+ ArrayList<user> getParticipants()
+ void setParticipants(ArrayList<user>)
+ String getExp()
+ void setExp(String)
+ String getDate()
+ void setDate(String)
+ String getHour()
+ void setHour(String)
+ String getMinute()
+ void setMinute(String)
+ int getDuration()
+ void setDuration(int)
+ String getEmailOfTrainer()
+ void setEmailOfTrainer(String)
}
class com.example.hgym.createEquipmentExercises {
~ EditText emailEdit
~ Button btnSave
~ String name
~ boolean isSaved
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
# void onCreate(Bundle)
+ void onClick(View)
+ boolean eqEx(equipmentExercise,equipmentExercise)
}
class com.example.hgym.equipmentExercise {
# double weight
+ <<Create>> equipmentExercise(String,String,String,String,double)
+ <<Create>> equipmentExercise()
+ double getWeight()
+ void setWeight(double)
}
class com.example.hgym.ShowOneGroup {
- TextView exp
- Button returnBut
- ImageView image
~ String gameId
~ group g
- FirebaseAuth mAuth
- FirebaseFirestore fDB
- FirebaseFirestore db
- FirebaseUser currentUser
- CollectionReference audioColl
~ StorageReference storageRef
~ FirebaseStorage storage
~ String itImagePath
~ Intent intent
~ String path
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.DestinationActivity {
- Button goGroups
~ FirebaseAuth mAuth
~ FirebaseFirestore db
~ FirebaseUser currentUser
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.Record {
~ String pathName
~ long duration
~ String date
+ <<Create>> Record(String,long)
+ <<Create>> Record()
+ String getPathName()
+ void setPathName(String)
+ long getDuration()
+ void setDuration(long)
+ void setDate(String)
+ String getDate()
}
class com.example.hgym.AudioRecordActivity {
- {static} String LOG_TAG
- {static} int REQUEST_RECORD_AUDIO_PERMISSION
- {static} String fileName
~ FirebaseAuth mAuth
~ FirebaseFirestore db
~ FirebaseUser currentUser
- ListView lvMethods
- ArrayList<Record> method
~ FirebaseStorage storage
~ StorageReference storageRef
~ Task<ListResult> recordRef
- RecordButton recordButton
- MediaRecorder recorder
- CollectionReference audioColl
~ long duration
- PlayButton playButton
- MediaPlayer player
- Date date1
- boolean permissionToRecordAccepted
- String[] permissions
- StorageReference mStorage
- ProgressDialog mProgress
+ void onRequestPermissionsResult(int,String[],int[])
- void onRecord(boolean)
- void onPlay(boolean)
- void startPlaying()
- void stopPlaying()
- void startRecording()
+ void onCreate(Bundle)
- void loadGamesToListView()
- void stopRecording()
+ String itemPath()
- void uploadAudio()
+ void onStop()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void goToListVIew()
}
class com.example.hgym.AudioRecordActivity$RecordButton {
~ boolean mStartRecording
~ OnClickListener clicker
+ <<Create>> RecordButton(Context)
}
class com.example.hgym.AudioRecordActivity$PlayButton {
~ boolean mStartPlaying
~ OnClickListener clicker
+ <<Create>> PlayButton(Context)
}
class com.example.hgym.makeAdapter {
+ <<Create>> makeAdapter(Context,ArrayList<nonEquipmentExercise>)
+ View getView(int,View,ViewGroup)
}
class com.example.hgym.ShowGroupsTrainer {
- ListView lvMethods
~ Button join
~ ArrayList<group> alMethods
~ TextView text
~ FirebaseFirestore db
- FirebaseAuth mAuth
~ FirebaseUser currentUser
~ ArrayList<String> emails
- CollectionReference audioColl
# void onCreate(Bundle)
- void loadGamesToListView1()
- void loadGamesToListView2()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.hgym.userDetailsActivity {
~ Button btnGoBack
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
- TextView year
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.user {
# String firstname
# String lastname
# String itImagePath
# int dayOfBirth
# int monthOfBirth
# int yearOfBirth
# String email
# String roll
# String password
# ArrayList<equipmentExercise> equipmentExercise
# ArrayList<nonEquipmentExercise> nonEquipmentExercise
+ <<Create>> user(String,String,int,int,int,String,String,String)
+ <<Create>> user(String,String,int,int,int,String,String,String,String)
+ <<Create>> user()
+ <<Create>> user(String,String,int,int,int,String,String,String,ArrayList<equipmentExercise>,ArrayList<nonEquipmentExercise>)
+ String getFirstname()
+ void setFirstname(String)
+ String getLastname()
+ void setLastname(String)
+ int getDayOfBirth()
+ void setDayOfBirth(int)
+ int getMonthOfBirth()
+ void setMonthOfBirth(int)
+ int getYearOfBirth()
+ void setYearOfBirth(int)
+ String getEmail()
+ void setEmail(String)
+ String getRoll()
+ void setRoll(String)
+ String getPassword()
+ void setPassword(String)
+ ArrayList<equipmentExercise> getEquipmentExercise()
+ ArrayList<nonEquipmentExercise> getNonEquipmentExercise()
+ void setEquipmentExercise(ArrayList<equipmentExercise>)
+ void setNonEquipmentExercise(ArrayList<nonEquipmentExercise>)
+ String getItImagePath()
+ void setItImagePath(String)
}
class com.example.hgym.AllTheGroups {
- ListView lvMethods
~ ArrayList<group> alMethods
~ FirebaseFirestore db
- FirebaseAuth mAuth
~ FirebaseUser currentUser
- CollectionReference audioColl
~ ArrayList<String> emails
# void onCreate(Bundle)
- void loadGamesToListView()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.hgym.MyAppGlideModule {
+ void registerComponents(Context,Glide,Registry)
}
class com.example.hgym.Profile {
~ Button btnGoBack
~ FirebaseAuth mAuth
~ FirebaseFirestore db
~ FirebaseUser currentUser
~ ImageView photo
~ String itImagePath
~ StorageReference storageRef
~ FirebaseStorage storage
~ Uri uri
~ Intent galleryAdd
~ {static} int REQUEST_IMAGE_CAPTURE
- TextView year
~ String emailS
~ int dayS
~ ActivityResultLauncher<Intent> someActivityResultLauncher
# void onCreate(Bundle)
+ void onClick(View)
- void openCamera()
+ Uri getImageUri(Context,Bitmap)
+ void onActivityResult(int,int,Intent)
- void dispatchTakePictureIntent()
+ String itemPath()
- void UploadPhoto2()
}
class com.example.hgym.makeRollAdapter {
+ <<Create>> makeRollAdapter(Context,ArrayList<trainerForListView>)
+ View getView(int,View,ViewGroup)
}
class com.example.hgym.audioAdapter {
+ <<Create>> audioAdapter(Context,ArrayList<Record>)
+ View getView(int,View,ViewGroup)
}
class com.example.hgym.showNonExercises {
- TextView exp
- Button returnBut
~ String gameId
- FirebaseAuth mAuth
- FirebaseFirestore fDB
- FirebaseFirestore db
- FirebaseUser currentUser
~ Intent intent
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.groupAdapter {
+ <<Create>> groupAdapter(Context,ArrayList<group>)
+ View getView(int,View,ViewGroup)
}
class com.example.hgym.showExercises {
- TextView exp
- Button returnBut
~ String gameId
- FirebaseAuth mAuth
- FirebaseFirestore fDB
- FirebaseFirestore db
- FirebaseUser currentUser
~ Intent intent
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.makeAdapterPos {
+ <<Create>> makeAdapterPos(Context,ArrayList<equipmentExercise>)
+ View getView(int,View,ViewGroup)
}
class com.example.hgym.nonEquipmentExercise {
# double duration
+ <<Create>> nonEquipmentExercise(String,String,String,String,double)
+ <<Create>> nonEquipmentExercise()
+ double getDuration()
+ void setDuration(double)
}
class com.example.hgym.showParticipent {
~ Button btnGoBack
~ FirebaseAuth mAuth
~ FirebaseFirestore db
~ FirebaseUser currentUser
~ ImageView photo
~ String itImagePath
~ StorageReference storageRef
~ FirebaseStorage storage
~ Uri uri
~ Intent galleryAdd
~ {static} int REQUEST_IMAGE_CAPTURE
- TextView year
~ String emailS
~ int dayS
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.trainerForListView {
- String firstName
- String LastName
- String Email
+ <<Create>> trainerForListView(String,String,String)
+ String getEmail()
+ String getFirstName()
+ String getLastName()
+ void setEmail(String)
+ void setFirstName(String)
+ void setLastName(String)
}
class com.example.hgym.Animation {
# void onCreate(Bundle)
}
class com.example.hgym.MyService {
- {static} String CHANNEL_ID
~ NotificationManager manager
+ <<Create>> MyService()
+ IBinder onBind(Intent)
+ int onStartCommand(Intent,int,int)
+ void ChannelCreation()
+ void CreateNotification()
}
class com.example.hgym.exercise {
# String muscleGroup
# String name
# String levelOfDifficulty
# String explanation
+ <<Create>> exercise()
+ <<Create>> exercise(String,String,String,String)
+ String getExplanation()
+ void setExplanation(String)
+ String getMuscleGroup()
+ void setMuscleGroup(String)
+ String getName()
+ void setName(String)
+ String getLevelOfDifficulty()
+ void setLevelOfDifficulty(String)
}
class com.example.hgym.BlankFragment {
~ View view
- FirebaseAuth mAuth
- FirebaseFirestore db
- ListView lvMethods
~ ArrayList<equipmentExercise> Methods
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void loadGamesToListView()
}
class com.example.hgym.SaveUser {
~ FirebaseFirestore db
~ EditText nameEdit
~ Button btnSave
~ String email
~ String day
~ boolean isSaved
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.createNonEquipmentExercises {
~ EditText emailEdit
~ Button btnSave
~ String name
~ boolean isSaved
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
~ FirebaseFirestore db
# void onCreate(Bundle)
+ void onClick(View)
+ boolean eqEx(nonEquipmentExercise,nonEquipmentExercise)
}
class com.example.hgym.alarmActivity {
- Button selectedTimeBtn
- MaterialTimePicker picker
- TextView textView
- Calendar calendar
- AlarmManager alarmManager
- PendingIntent pendingIntent
~ FirebaseAuth mAuth
~ FirebaseFirestore db
~ FirebaseUser currentUser
~ String year
# void onCreate(Bundle)
- void createNotificationChannel()
+ void onClick(View)
+ void cancelAlarm()
+ void setAlarm()
- void showTimePicker()
}
class com.example.hgym.MainActivityTrainer {
~ ImageButton createUser
# void onCreate(Bundle)
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void goToListVIew()
}
class com.example.hgym.LogInActivity {
- {static} String TAG
- FirebaseAuth mAuth
~ Button login
~ String password
~ EditText emailEdit
~ FirebaseFirestore db
# void onCreate(Bundle)
+ void onStart()
- void updateUI(FirebaseUser)
- void reload()
- void moveToMenu()
+ void onClick(View)
+ void goToLogin()
}
class com.example.hgym.createUserActivity {
~ FirebaseFirestore db
~ EditText nameEdit
~ Button btnSave
~ String email
~ String day
~ boolean isSaved
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.hgym.ShowGroups {
- ListView lvMethods
~ Button join
~ ArrayList<group> alMethods
~ TextView text
~ FirebaseFirestore db
- FirebaseAuth mAuth
~ FirebaseUser currentUser
~ ArrayList<String> emails
- CollectionReference audioColl
# void onCreate(Bundle)
- void loadGamesToListView1()
- void loadGamesToListView2()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.hgym.AlarmReceiver {
+ void onReceive(Context,Intent)
}
class com.example.hgym.CreateGroup {
~ FirebaseFirestore db
- CollectionReference audioColl
~ EditText dateE
~ MaterialDatePicker materialDatePicker
~ Button btnSave
~ ImageView btnDate
- Calendar calendar
~ int dayI
- MaterialTimePicker picker
- StorageReference mStorage
~ String hour
~ boolean isSaved
~ FirebaseAuth mAuth
~ FirebaseUser currentUser
# void onCreate(Bundle)
+ String itemPath()
- void showDatePickerDialog()
+ void onDateSet(DatePicker,int,int,int)
- void showTimePicker()
+ void onClick(View)
}
class com.example.hgym.listViewActivity {
~ FirebaseAuth mAuth
~ FirebaseFirestore db
~ ListView lvMethods
~ ArrayList<nonEquipmentExercise> alMethods
~ Button firstFragmentBtn
~ TextView textView
# void onCreate(Bundle)
- void replaceFragment(Fragment)
- void loadGamesToListView()
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.hgym.Player {
- TextView name
- Button returnBut
~ String path
- FirebaseAuth mAuth
- FirebaseFirestore fDB
~ FirebaseFirestore db
- FirebaseUser currentUser
- MediaPlayer player
~ FirebaseStorage storage
~ StorageReference storageRef
~ Intent intent
~ String gameId
# void onCreate(Bundle)
- void startPlaying()
+ void onClick(View)
}
class com.example.hgym.MenuActivity {
~ ImageButton createUser
# void onCreate(Bundle)
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
+ void goToListVIew()
}
class com.example.hgym.BlankFragmentNon {
~ View view
- FirebaseAuth mAuth
- FirebaseFirestore db
- ListView lvMethods
~ ArrayList<nonEquipmentExercise> alMethods
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void loadGamesToListView()
}


androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.listViewRollActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.MainActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.MainActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.userDetailsByRollActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.userDetailsByRollActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.createEquipmentExercises
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.createEquipmentExercises
com.example.hgym.exercise <|-- com.example.hgym.equipmentExercise
com.example.hgym.OnClickListener <|.. com.example.hgym.ShowOneGroup
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.ShowOneGroup
com.example.hgym.OnClickListener <|.. com.example.hgym.DestinationActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.DestinationActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.AudioRecordActivity
com.example.hgym.AudioRecordActivity +.. com.example.hgym.AudioRecordActivity$RecordButton
com.example.hgym.Button <|-- com.example.hgym.AudioRecordActivity$RecordButton
com.example.hgym.AudioRecordActivity +.. com.example.hgym.AudioRecordActivity$PlayButton
com.example.hgym.Button <|-- com.example.hgym.AudioRecordActivity$PlayButton
android.widget.ArrayAdapter <|-- com.example.hgym.makeAdapter
com.example.hgym.OnClickListener <|.. com.example.hgym.ShowGroupsTrainer
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.ShowGroupsTrainer
com.example.hgym.OnClickListener <|.. com.example.hgym.userDetailsActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.userDetailsActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.AllTheGroups
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.AllTheGroups
com.bumptech.glide.module.AppGlideModule <|-- com.example.hgym.MyAppGlideModule
com.example.hgym.OnClickListener <|.. com.example.hgym.Profile
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.Profile
android.widget.ArrayAdapter <|-- com.example.hgym.makeRollAdapter
android.widget.ArrayAdapter <|-- com.example.hgym.audioAdapter
com.example.hgym.OnClickListener <|.. com.example.hgym.showNonExercises
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.showNonExercises
android.widget.ArrayAdapter <|-- com.example.hgym.groupAdapter
com.example.hgym.OnClickListener <|.. com.example.hgym.showExercises
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.showExercises
android.widget.ArrayAdapter <|-- com.example.hgym.makeAdapterPos
com.example.hgym.exercise <|-- com.example.hgym.nonEquipmentExercise
com.example.hgym.OnClickListener <|.. com.example.hgym.showParticipent
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.showParticipent
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.Animation
android.app.Service <|-- com.example.hgym.MyService
androidx.fragment.app.Fragment <|-- com.example.hgym.BlankFragment
com.example.hgym.OnClickListener <|.. com.example.hgym.SaveUser
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.SaveUser
com.example.hgym.OnClickListener <|.. com.example.hgym.createNonEquipmentExercises
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.createNonEquipmentExercises
com.example.hgym.OnClickListener <|.. com.example.hgym.alarmActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.alarmActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.MainActivityTrainer
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.MainActivityTrainer
com.example.hgym.OnClickListener <|.. com.example.hgym.LogInActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.LogInActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.createUserActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.createUserActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.ShowGroups
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.ShowGroups
android.content.BroadcastReceiver <|-- com.example.hgym.AlarmReceiver
com.example.hgym.OnClickListener <|.. com.example.hgym.CreateGroup
com.example.hgym.OnDateSetListener <|.. com.example.hgym.CreateGroup
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.CreateGroup
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.listViewActivity
com.example.hgym.OnClickListener <|.. com.example.hgym.Player
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.Player
com.example.hgym.OnClickListener <|.. com.example.hgym.MenuActivity
androidx.appcompat.app.AppCompatActivity <|-- com.example.hgym.MenuActivity
androidx.fragment.app.Fragment <|-- com.example.hgym.BlankFragmentNon
@enduml